In [45]:
print ("hello wroeld")


hello wroeld


In [46]:
import numpy as np

In [47]:
a=np.array([[67,7,89],[34,2,56],[34,2,56],[34,2,56]])
b=np.array([[34,2,56],[34,2,56],[34,2,56],])


print("shape of a",a.shape)
print("shape of b",b.shape)
d=a @ b
print("matrix multiplication of a anmd b is\n",d)


shape of a (4, 3)
shape of b (3, 3)
matrix multiplication of a anmd b is
 [[5542  326 9128]
 [3128  184 5152]
 [3128  184 5152]
 [3128  184 5152]]


In [48]:
import urllib.request
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [49]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
 

In [50]:
a+2

array([[69,  9, 91],
       [36,  4, 58],
       [36,  4, 58],
       [36,  4, 58]])

In [51]:
a

array([[67,  7, 89],
       [34,  2, 56],
       [34,  2, 56],
       [34,  2, 56]])

In [52]:
b-2

array([[32,  0, 54],
       [32,  0, 54],
       [32,  0, 54]])

In [53]:
b

array([[34,  2, 56],
       [34,  2, 56],
       [34,  2, 56]])

In [54]:
#a+b

In [55]:
b=np.array([[34,2,56],[34,2,56],[34,2,56]])
#a+b




In [56]:
a%2

array([[1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [57]:
b*6

array([[204,  12, 336],
       [204,  12, 336],
       [204,  12, 336]])

In [58]:
a*b                  

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [ ]:
(a<=b).sum()

9

In [ ]:
a.shape


(4, 3)

In [ ]:
b

array([[34,  2, 56],
       [34,  2, 56],
       [34,  2, 56],
       [34,  2, 56]])

In [ ]:
a==b

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a[1,2]

56

In [ ]:
c=np.array([[[34,2,56],[34,2,56],[34,2,56],
            [34,2,56],[34,2,56],[34,2,56],
            [34,2,56],[34,24,56],[34,2,56],[34,2,56]],
            [[34,21,56],[34,2,56],[34,2,56],
            [34,2,56],[34,2,56],[34,2,56],
            [34,2,56],[34,2,56],[34,2,56],[34,2,56]]])
c.shape

(2, 10, 3)

In [ ]:
c[:2,:5,:1]

array([[[34],
        [34],
        [34],
        [34],
        [34]],

       [[34],
        [34],
        [34],
        [34],
        [34]]])

In [ ]:
np.zeros((2,3,5))


(4, 3)

In [ ]:
np.full((2,3,9),23)

array([[[23, 23, 23, 23, 23, 23, 23, 23, 23],
        [23, 23, 23, 23, 23, 23, 23, 23, 23],
        [23, 23, 23, 23, 23, 23, 23, 23, 23]],

       [[23, 23, 23, 23, 23, 23, 23, 23, 23],
        [23, 23, 23, 23, 23, 23, 23, 23, 23],
        [23, 23, 23, 23, 23, 23, 23, 23, 23]]])

In [ ]:
c=np.arange(10,56,3)
c.shape

(16,)

In [ ]:
c.reshape(2,-1,2)

array([[[10, 13],
        [16, 19],
        [22, 25],
        [28, 31]],

       [[34, 37],
        [40, 43],
        [46, 49],
        [52, 55]]])

In [ ]:
d=np.linspace(1,18,7)
d

array([ 1.        ,  3.83333333,  6.66666667,  9.5       , 12.33333333,
       15.16666667, 18.        ])

In [ ]:
e=np.eye(9,9)
e

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
f=np.dot(a,b)
b=np.array([[34,  2, 56],
       [34,  2, 56],
       [34,  2, 56],
       ])
print(f)
g=np.mean(f)
h=np.median(f)
i=np.std(f)
print(g)
print(i)
print(h)
j=np.max(f)
k=np.min(f)
print(j,k)
print(a)
l=np.where(f<3000,f,f%10)
print(l)
m,n,o,p=np.sin(f),np.cos(f),np.tan(f),np.arcsin(f)
print(m,"\n",n,"\n",o,"\n",p)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [ ]:
import os

In [ ]:
os.getcwd()
os.listdir(".")
os.makedirs('.\data1')
'data' in os.listdir('.')

In [ ]:
os.listdir('.\data1')

In [ ]:
from urllib.request import urlretrieve
italy_covid_url = 'https://gist.githubusercontent.com/aakashns/f6a004fa20c84fec53262f9a8bfee775/raw/f309558b1cf5103424cef58e2ecb8704dcd4d74c/italy-covid-daywise.csv'

urlretrieve(italy_covid_url, 'italy-covid-daywise.csv')
import pandas as pd
covid_df=pd.read_csv('italy-covid-daywise.csv')
print(covid_df)

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]


In [ ]:
covid_df.describe()

new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

In [ ]:
print(covid_df.shape)
print(covid_df['new_cases'])
print(covid_df['new_cases'][233])
print(covid_df.at[243,'new_cases'])
print(covid_df[['new_cases','new_deaths']])
print(covid_df.head(5))
print(covid_df.tail(5))



(248, 4)
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...  
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64
642.0
1444.0
     new_cases  new_deaths
0          0.0         0.0
1          0.0         0.0
2          0.0         0.0
3          0.0         0.0
4          0.0         0.0
..         ...         ...
243     1444.0         1.0
244     1365.0         4.0
245      996.0         6.0
246      975.0         8.0
247     1326.0         6.0

[248 rows x 2 columns]
         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN
           date  new_cases  new_deaths  new_tests
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    4

In [ ]:
covid_df.new_tests.first_valid_index()

111

In [ ]:
print(covid_df[109:118])
covid_df.sample(2)


           date  new_cases  new_deaths  new_tests
109  2020-04-18     3493.0       575.0        NaN
110  2020-04-19     3491.0       480.0        NaN
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0
114  2020-04-23     3370.0       437.0    37083.0
115  2020-04-24     2646.0       464.0    95273.0
116  2020-04-25     3021.0       420.0    38676.0
117  2020-04-26     2357.0       415.0    24113.0


date  new_cases  new_deaths  new_tests
185  2020-07-03      201.0        30.0    25680.0
228  2020-08-15      574.0         3.0    25937.0

In [ ]:
total_newcase=covid_df.new_cases.sum()
initial_test=953102
total_tests=covid_df.new_tests.sum()
initial_cases=56222
print("the total no. of test {} and the total test {}".format (total_tests+initial_test,total_newcase+initial_cases))
print("the no, of the positive rate={:.2f}".format(((total_tests+initial_test)/(total_newcase+initial_cases))))

the total no. of test 5232558.0 and the total test 327737.0
the no, of the positive rate=15.97


In [ ]:
high_no_cases=covid_df.new_cases>1000
high_no_cases

0      False
1      False
2      False
3      False
4      False
       ...  
243     True
244     True
245    False
246    False
247     True
Name: new_cases, Length: 248, dtype: bool

In [ ]:
covid_df[high_no_cases]

date  new_cases  new_deaths  new_tests
68   2020-03-08     1247.0        36.0        NaN
69   2020-03-09     1492.0       133.0        NaN
70   2020-03-10     1797.0        98.0        NaN
72   2020-03-12     2313.0       196.0        NaN
73   2020-03-13     2651.0       189.0        NaN
..          ...        ...         ...        ...
241  2020-08-28     1409.0         5.0    65135.0
242  2020-08-29     1460.0         9.0    64294.0
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
247  2020-09-03     1326.0         6.0        NaN

[72 rows x 4 columns]

In [ ]:
lowcases=covid_df[covid_df.new_cases<1000]
print(lowcases)

                                                  date  new_cases  new_deaths  \
0    <bound method _inherit_from_data.<locals>.meth...        0.0         0.0   
1    <bound method _inherit_from_data.<locals>.meth...        0.0         0.0   
2    <bound method _inherit_from_data.<locals>.meth...        0.0         0.0   
3    <bound method _inherit_from_data.<locals>.meth...        0.0         0.0   
4    <bound method _inherit_from_data.<locals>.meth...        0.0         0.0   
..                                                 ...        ...         ...   
235  <bound method _inherit_from_data.<locals>.meth...      947.0         9.0   
238  <bound method _inherit_from_data.<locals>.meth...      953.0         4.0   
239  <bound method _inherit_from_data.<locals>.meth...      876.0         4.0   
245  <bound method _inherit_from_data.<locals>.meth...      996.0         6.0   
246  <bound method _inherit_from_data.<locals>.meth...      975.0         8.0   

     new_tests  year  month

In [ ]:
covid_df['date']=pd.to_datetime(covid_df.date)

TypeError: <class 'method'> is not convertible to datetime, at position 0